# @package _global_

name: 'fracatlas'
batch_size: 32
num_workers: 4

params:
  img_dir: "${hydra:runtime.cwd}/data/FracAtlas/images"
  report_dir: "${hydra:runtime.cwd}/data/FracAtlas/reports"
  csv_split_path: "${hydra:runtime.cwd}/data/FracAtlas/fracatlas-split.csv"
  csv_labels_path: "${hydra:runtime.cwd}/data/FracAtlas/fracatlas-labels.csv"


  # Linh hoạt: Dataset khác có thể có danh sách bệnh khác
  pathologies: [
    'fractured',
  ]