# @package _global_

name: 'mimic_cxr'
batch_size: 64
num_workers: 4

params:
  img_dir: "${hydra:runtime.cwd}/data/MIMIC_CXR/imgs"
  report_dir: "${hydra:runtime.cwd}/data/MIMIC_CXR/reports"
  csv_split_path: "${hydra:runtime.cwd}/data/MIMIC_CXR/mimic-cxr-2.0.0-split.csv"
  csv_chexpert_path: "${hydra:runtime.cwd}/data/MIMIC_CXR/mimic-cxr-2.0.0-chexpert.csv"
  
  # THÊM THAM SỐ NÀY: Tỉ lệ dữ liệu train muốn sử dụng (0.1 = 10%)
  train_ratio: 0.1

  # Linh hoạt: Dataset khác có thể có danh sách bệnh khác
  pathologies: [
    'Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema', 
    'Enlarged Cardiomediastinum', 'Fracture', 'Lung Lesion', 
    'Lung Opacity', 'No Finding', 'Pleural Effusion', 
    'Pleural Other', 'Pneumonia', 'Pneumothorax', 'Support Devices'
  ]
  uncertainty_strategy: "U-Ones"