"""Cung cấp công cụ nghiên cứu generate requirement cho XBone-Net.

Notes
-----
Mô-đun này thuộc cơ sở mã nguồn nghiên cứu XBone-Net và giữ các quy ước dùng chung của dự án.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib.metadata as metadata
import os
from pathlib import Path
import re
import sys
from typing import Iterable


DEFAULT_EXCLUDED_DIRS = {
    ".git",
    ".agents",
    ".vscode",
    "__pycache__",
    "checkpoints",
    "data",
    "outputs",
    "pretrained",
    "results",
    "runs",
    "tmp_trainer",
}

# Thiết lập thành phần dùng chung cho quy trình xử lý của mô-đun.
# Thiết lập thành phần dùng chung cho quy trình xử lý của mô-đun.
# trong khi src/utils/metrics.py nhập trực tiếp gói evaluate của Hugging Face.
MODULE_TO_DISTRIBUTION = {
    "PIL": "Pillow",
    "evaluate": "evaluate",
    "hydra": "hydra-core",
    "medclip": "MedCLIP",
    "open_clip": "open-clip-torch",
    "sklearn": "scikit-learn",
    "yaml": "PyYAML",
}

# Thiết lập thành phần dùng chung cho quy trình xử lý của mô-đun.
# Thiết lập giá trị trung gian cho bước xử lý tiếp theo.
RUNTIME_DISTRIBUTIONS = {
    "accelerate": "required by transformers.Trainer at runtime",
    "deep-translator": (
        "used by data/CTCH/preprocess_ctch.py to materialize English OOD reports"
    ),
    "tensorboard": (
        "required by torch.utils.tensorboard.SummaryWriter in TrainingLogger"
    ),
}

# Xử lý bộ mã hóa nền tảng theo giao diện tương ứng.
# Thiết lập thành phần dùng chung cho quy trình xử lý của mô-đun.
# Xử lý bộ mã hóa nền tảng theo giao diện tương ứng.
# Thiết lập giá trị trung gian cho bước xử lý tiếp theo.
CONDITIONAL_RUNTIME_DISTRIBUTIONS = {
    "medclip": {
        "nltk": "imported by MedCLIPProcessor",
        "requests": "used to resolve pretrained MedCLIP weight URLs",
        "timm": "provides MedCLIP's Swin vision layers",
        "wget": "downloads pretrained MedCLIP weights",
    }
}

# Xử lý bộ mã hóa nền tảng theo giao diện tương ứng.
# Thiết lập thành phần dùng chung cho quy trình xử lý của mô-đun.
# Xử lý bộ mã hóa nền tảng theo giao diện tương ứng.
# Xử lý bộ mã hóa nền tảng theo giao diện tương ứng.
# Thiết lập giá trị trung gian cho bước xử lý tiếp theo.
MANUAL_DISTRIBUTIONS = {
    "medclip": "upstream metadata conflicts with the project's Transformers version",
}

HEADER = (
    "# Auto-generated by tools/generate_requirement.py.\n"
    "# Contains direct and required runtime dependencies; do not edit manually.\n"
)


def normalize_distribution_name(name: str) -> str:
    """Chuẩn hóa distribution name cho bước xử lý hiện tại.

    Parameters
    ----------
    name : str
        Tên hoặc khóa định danh của giá trị.

    Returns
    -------
    str
        Kết quả được tạo bởi bước xử lý của hàm.
    """
    return re.sub(r"[-_.]+", "-", name).lower()


def iter_python_files(root: Path, excluded_dirs: set[str]) -> Iterable[Path]:
    """Thực hiện bước iter python files trong quy trình hiện tại.

    Parameters
    ----------
    root : Path
        Đường dẫn tài nguyên được sử dụng.
    excluded_dirs : set[str]
        Giá trị ``excluded_dirs`` được sử dụng trong phép xử lý.

    Yields
    ------
    Iterable[Path]
        Phần tử tiếp theo do bộ sinh cung cấp.
    """
    for current_dir, dir_names, file_names in os.walk(root):
        dir_names[:] = sorted(name for name in dir_names if name not in excluded_dirs)
        current_path = Path(current_dir)
        for file_name in sorted(file_names):
            if file_name.endswith(".py"):
                yield current_path / file_name


def discover_local_modules(root: Path, excluded_dirs: set[str]) -> set[str]:
    """Thực hiện bước discover local modules trong quy trình hiện tại.

    Parameters
    ----------
    root : Path
        Đường dẫn tài nguyên được sử dụng.
    excluded_dirs : set[str]
        Giá trị ``excluded_dirs`` được sử dụng trong phép xử lý.

    Returns
    -------
    set[str]
        Kết quả được tạo bởi bước xử lý của hàm.
    """
    local_modules = {path.stem for path in root.glob("*.py")}
    for child in root.iterdir():
        if child.is_dir() and child.name not in excluded_dirs:
            if (child / "__init__.py").exists() or any(child.glob("*.py")):
                local_modules.add(child.name)
    return local_modules


def scan_imports(root: Path, excluded_dirs: set[str]) -> dict[str, set[Path]]:
    """Thực hiện bước scan imports trong quy trình hiện tại.

    Parameters
    ----------
    root : Path
        Đường dẫn tài nguyên được sử dụng.
    excluded_dirs : set[str]
        Giá trị ``excluded_dirs`` được sử dụng trong phép xử lý.

    Returns
    -------
    dict[str, set[Path]]
        Kết quả được tạo bởi bước xử lý của hàm.

    Raises
    ------
    RuntimeError
        Khi dữ liệu hoặc trạng thái đầu vào không hợp lệ.
    """
    imports: dict[str, set[Path]] = {}
    syntax_errors: list[str] = []

    for path in iter_python_files(root, excluded_dirs):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8-sig"), filename=str(path))
        except (OSError, SyntaxError, UnicodeError) as exc:
            syntax_errors.append(f"{path.relative_to(root)}: {exc}")
            continue

        for node in ast.walk(tree):
            modules: list[str] = []
            if isinstance(node, ast.Import):
                modules = [alias.name.split(".", 1)[0] for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                modules = [node.module.split(".", 1)[0]]

            for module in modules:
                imports.setdefault(module, set()).add(path.relative_to(root))

    if syntax_errors:
        details = "\n".join(f"  - {error}" for error in syntax_errors)
        raise RuntimeError(f"Could not parse every Python file:\n{details}")
    return imports


def canonical_distribution_name(name: str) -> str:
    """Thực hiện bước canonical distribution name trong quy trình hiện tại.

    Parameters
    ----------
    name : str
        Tên hoặc khóa định danh của giá trị.

    Returns
    -------
    str
        Kết quả được tạo bởi bước xử lý của hàm.
    """
    try:
        return metadata.metadata(name).get("Name", name)
    except metadata.PackageNotFoundError:
        return name


def resolve_distributions(
    imports: dict[str, set[Path]],
    local_modules: set[str],
) -> tuple[dict[str, set[str]], list[str]]:
    """Xác định distributions cho bước xử lý hiện tại.

    Parameters
    ----------
    imports : dict[str, set[Path]]
        Giá trị ``imports`` được sử dụng trong phép xử lý.
    local_modules : set[str]
        Giá trị ``local_modules`` được sử dụng trong phép xử lý.

    Returns
    -------
    tuple[dict[str, set[str]], list[str]]
        Kết quả được tạo bởi bước xử lý của hàm.
    """
    package_map = metadata.packages_distributions()
    resolved: dict[str, set[str]] = {}
    unresolved: list[str] = []

    for module in sorted(imports):
        if module in MODULE_TO_DISTRIBUTION:
            candidates = [MODULE_TO_DISTRIBUTION[module]]
        elif module in sys.stdlib_module_names or module in local_modules:
            continue
        else:
            candidates = package_map.get(module, [])

        if not candidates:
            unresolved.append(module)
            continue

        # Bước hỗ trợ để xác định distributions cho bước xử lý hiện tại.
        # Bước hỗ trợ để xác định distributions cho bước xử lý hiện tại.
        # Thiết lập giá trị trung gian cho bước xử lý tiếp theo.
        installed = []
        for candidate in candidates:
            try:
                metadata.version(candidate)
                installed.append(candidate)
            except metadata.PackageNotFoundError:
                pass
        if len(installed) != 1:
            unresolved.append(
                f"{module} (distribution candidates: {', '.join(candidates) or 'none'})"
            )
            continue

        distribution = canonical_distribution_name(installed[0])
        resolved.setdefault(distribution, set()).add(module)

    runtime_distributions = dict(RUNTIME_DISTRIBUTIONS)
    resolved_names = {normalize_distribution_name(name) for name in resolved}
    for trigger, dependencies in CONDITIONAL_RUNTIME_DISTRIBUTIONS.items():
        if trigger in resolved_names:
            runtime_distributions.update(dependencies)

    for distribution in runtime_distributions:
        try:
            metadata.version(distribution)
        except metadata.PackageNotFoundError:
            unresolved.append(
                f"runtime dependency {distribution} "
                f"({runtime_distributions[distribution]})"
            )
            continue
        resolved.setdefault(canonical_distribution_name(distribution), set()).add("<runtime>")

    return resolved, unresolved


def render_requirements(distributions: Iterable[str], pin_versions: bool) -> str:
    """Kết xuất requirements cho bước xử lý hiện tại.

    Parameters
    ----------
    distributions : Iterable[str]
        Giá trị ``distributions`` được sử dụng trong phép xử lý.
    pin_versions : bool
        Giá trị ``pin_versions`` được sử dụng trong phép xử lý.

    Returns
    -------
    str
        Kết quả được tạo bởi bước xử lý của hàm.
    """
    distributions = sorted(distributions, key=normalize_distribution_name)
    manual = [
        name
        for name in distributions
        if normalize_distribution_name(name) in MANUAL_DISTRIBUTIONS
    ]
    installable = [name for name in distributions if name not in manual]

    lines = []
    for distribution in installable:
        if pin_versions:
            # Chọn thiết bị và độ chính xác tính toán phù hợp.
            # Bước hỗ trợ để kết xuất requirements cho bước xử lý hiện tại.
            # Chuẩn bị và ghi tài nguyên đầu ra theo định dạng yêu cầu.
            version = metadata.version(distribution).split("+", 1)[0]
            lines.append(f"{distribution}=={version}")
        else:
            lines.append(distribution)

    manual_lines = []
    if manual:
        manual_lines.extend(
            [
                "#",
                "# Manual compatibility install(s), required only by the corresponding baseline:",
            ]
        )
        for distribution in manual:
            requirement = distribution
            if pin_versions:
                version = metadata.version(distribution).split("+", 1)[0]
                requirement = f"{distribution}=={version}"
            reason = MANUAL_DISTRIBUTIONS[normalize_distribution_name(distribution)]
            manual_lines.append(f"# {requirement}: {reason}.")
            manual_lines.append(f"#   python -m pip install --no-deps {requirement}")

    body = "\n".join(lines + manual_lines)
    return HEADER + body + "\n"


def existing_requirement_names(path: Path) -> set[str]:
    """Thực hiện bước existing requirement names trong quy trình hiện tại.

    Parameters
    ----------
    path : Path
        Đường dẫn tài nguyên được sử dụng.

    Returns
    -------
    set[str]
        Kết quả được tạo bởi bước xử lý của hàm.
    """
    if not path.exists():
        return set()
    names = set()
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", "-")):
            continue
        name = re.split(r"[<>=!~;\[]", line, maxsplit=1)[0].strip()
        if name:
            names.add(normalize_distribution_name(name))
    return names


def build_parser() -> argparse.ArgumentParser:
    """Xây dựng parser cho bước xử lý hiện tại.

    Returns
    -------
    argparse.ArgumentParser
        Kết quả được tạo bởi bước xử lý của hàm.
    """
    default_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Generate requirements.txt from direct repository imports."
    )
    parser.add_argument("--root", type=Path, default=default_root)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--exclude", action="append", default=[])
    parser.add_argument("--no-pin", action="store_true", help="Omit installed versions.")
    parser.add_argument("--check", action="store_true", help="Fail if the output is stale.")
    parser.add_argument("--dry-run", action="store_true", help="Print without writing.")
    parser.add_argument("--verbose", action="store_true", help="Show import mappings.")
    return parser


def main() -> int:
    """Thực thi điểm vào chính của mô-đun.

    Returns
    -------
    int
        Kết quả được tạo bởi bước xử lý của hàm.
    """
    args = build_parser().parse_args()
    root = args.root.resolve()
    output = (args.output or root / "requirements.txt").resolve()
    excluded_dirs = DEFAULT_EXCLUDED_DIRS | set(args.exclude)

    imports = scan_imports(root, excluded_dirs)
    local_modules = discover_local_modules(root, excluded_dirs)
    distributions, unresolved = resolve_distributions(imports, local_modules)
    if unresolved:
        details = "\n".join(f"  - {item}" for item in unresolved)
        print(
            "Unable to map every external import to exactly one installed distribution:\n"
            f"{details}\n"
            "Install the missing package or add an explicit MODULE_TO_DISTRIBUTION mapping.",
            file=sys.stderr,
        )
        return 2

    content = render_requirements(distributions, pin_versions=not args.no_pin)
    old_content = output.read_text(encoding="utf-8-sig") if output.exists() else ""

    if args.verbose:
        for distribution in sorted(distributions, key=normalize_distribution_name):
            modules = ", ".join(sorted(distributions[distribution]))
            print(f"{distribution}: {modules}")

    if args.dry_run:
        print(content, end="")
        return 0

    if args.check:
        if old_content == content:
            manual_count = sum(
                normalize_distribution_name(name) in MANUAL_DISTRIBUTIONS
                for name in distributions
            )
            print(
                f"{output} is up to date "
                f"({len(distributions) - manual_count} installable + "
                f"{manual_count} manual dependencies)."
            )
            return 0
        print(f"{output} is out of date.", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                old_content.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(output),
                tofile="generated requirements",
            )
        )
        return 1

    old_names = existing_requirement_names(output)
    new_names = {
        normalize_distribution_name(name)
        for name in distributions
        if normalize_distribution_name(name) not in MANUAL_DISTRIBUTIONS
    }
    output.write_text(content, encoding="utf-8", newline="\n")
    manual_names = sorted(
        name
        for name in distributions
        if normalize_distribution_name(name) in MANUAL_DISTRIBUTIONS
    )
    print(f"Wrote {len(new_names)} installable dependencies to {output}")
    if manual_names:
        print("Documented manual compatibility installs: " + ", ".join(manual_names))
    if added := sorted(new_names - old_names):
        print("Added: " + ", ".join(added))
    if removed := sorted(old_names - new_names):
        print("Removed: " + ", ".join(removed))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
