"""Generate requirements.txt from direct imports in the XBone-Net repository.

Unlike ``pip freeze``, this script excludes transitive packages that the project
does not import.  It scans Python files with the AST, maps import names to their
installed distributions, adds documented runtime-only dependencies, and pins
versions from the active Python environment.

Run this script with the same environment used to train XBone-Net::

    python tools/generate_requirement.py

Use ``--check`` in CI to fail when requirements.txt is out of date.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib.metadata as metadata
import os
from pathlib import Path
import re
import sys
from typing import Iterable


DEFAULT_EXCLUDED_DIRS = {
    ".git",
    ".agents",
    ".vscode",
    "__pycache__",
    "checkpoints",
    "data",
    "outputs",
    "pretrained",
    "results",
    "runs",
    "tmp_trainer",
}

# Import names and PyPI distribution names are not always identical.  The
# evaluate override is also intentional: evaluate.py is a local entry point,
# while src/utils/metrics.py explicitly imports Hugging Face's evaluate package.
MODULE_TO_DISTRIBUTION = {
    "PIL": "Pillow",
    "evaluate": "evaluate",
    "hydra": "hydra-core",
    "medclip": "MedCLIP",
    "open_clip": "open-clip-torch",
    "sklearn": "scikit-learn",
    "yaml": "PyYAML",
}

# Hugging Face Trainer loads Accelerate at runtime instead of through a normal
# project import, so an AST-only scan cannot discover it.
RUNTIME_DISTRIBUTIONS = {
    "accelerate": "required by transformers.Trainer at runtime",
    "deep-translator": (
        "used by data/CTCH/preprocess_ctch.py to materialize English OOD reports"
    ),
}

# MedCLIP's package initializer and pretrained-weight loader use these modules,
# although XBone-Net does not import them directly. They must be installed when
# MedCLIP is discovered, because MedCLIP itself is installed with --no-deps (see
# MANUAL_DISTRIBUTIONS below).
CONDITIONAL_RUNTIME_DISTRIBUTIONS = {
    "medclip": {
        "nltk": "imported by MedCLIPProcessor",
        "requests": "used to resolve pretrained MedCLIP weight URLs",
        "timm": "provides MedCLIP's Swin vision layers",
        "wget": "downloads pretrained MedCLIP weights",
    }
}

# Upstream MedCLIP 0.0.3 declares transformers<=4.24.0, while XBone-Net uses a
# modern Transformers release and applies its compatibility shim in
# src/models/backbone/medclip_foundation.py. Listing both packages normally
# makes pip's resolver fail, so keep MedCLIP visible in the generated file but
# install it separately without its stale dependency metadata.
MANUAL_DISTRIBUTIONS = {
    "medclip": "upstream metadata conflicts with the project's Transformers version",
}

HEADER = (
    "# Auto-generated by tools/generate_requirement.py.\n"
    "# Contains direct and required runtime dependencies; do not edit manually.\n"
)


def normalize_distribution_name(name: str) -> str:
    """Return the PEP 503 comparison form of a distribution name."""
    return re.sub(r"[-_.]+", "-", name).lower()


def iter_python_files(root: Path, excluded_dirs: set[str]) -> Iterable[Path]:
    """Yield repository Python files without traversing data/output trees."""
    for current_dir, dir_names, file_names in os.walk(root):
        dir_names[:] = sorted(name for name in dir_names if name not in excluded_dirs)
        current_path = Path(current_dir)
        for file_name in sorted(file_names):
            if file_name.endswith(".py"):
                yield current_path / file_name


def discover_local_modules(root: Path, excluded_dirs: set[str]) -> set[str]:
    """Find top-level modules and namespace-package directories in the project."""
    local_modules = {path.stem for path in root.glob("*.py")}
    for child in root.iterdir():
        if child.is_dir() and child.name not in excluded_dirs:
            if (child / "__init__.py").exists() or any(child.glob("*.py")):
                local_modules.add(child.name)
    return local_modules


def scan_imports(root: Path, excluded_dirs: set[str]) -> dict[str, set[Path]]:
    """Collect absolute top-level import names and the files using each one."""
    imports: dict[str, set[Path]] = {}
    syntax_errors: list[str] = []

    for path in iter_python_files(root, excluded_dirs):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8-sig"), filename=str(path))
        except (OSError, SyntaxError, UnicodeError) as exc:
            syntax_errors.append(f"{path.relative_to(root)}: {exc}")
            continue

        for node in ast.walk(tree):
            modules: list[str] = []
            if isinstance(node, ast.Import):
                modules = [alias.name.split(".", 1)[0] for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                modules = [node.module.split(".", 1)[0]]

            for module in modules:
                imports.setdefault(module, set()).add(path.relative_to(root))

    if syntax_errors:
        details = "\n".join(f"  - {error}" for error in syntax_errors)
        raise RuntimeError(f"Could not parse every Python file:\n{details}")
    return imports


def canonical_distribution_name(name: str) -> str:
    """Use the installed package metadata's canonical display name when possible."""
    try:
        return metadata.metadata(name).get("Name", name)
    except metadata.PackageNotFoundError:
        return name


def resolve_distributions(
    imports: dict[str, set[Path]],
    local_modules: set[str],
) -> tuple[dict[str, set[str]], list[str]]:
    """Map imported modules to distributions and return unresolved import names."""
    package_map = metadata.packages_distributions()
    resolved: dict[str, set[str]] = {}
    unresolved: list[str] = []

    for module in sorted(imports):
        if module in MODULE_TO_DISTRIBUTION:
            candidates = [MODULE_TO_DISTRIBUTION[module]]
        elif module in sys.stdlib_module_names or module in local_modules:
            continue
        else:
            candidates = package_map.get(module, [])

        if not candidates:
            unresolved.append(module)
            continue

        # Multiple distributions can expose the same import namespace. Select
        # an installed candidate deterministically and require an override when
        # the ambiguity cannot be resolved.
        installed = []
        for candidate in candidates:
            try:
                metadata.version(candidate)
                installed.append(candidate)
            except metadata.PackageNotFoundError:
                pass
        if len(installed) != 1:
            unresolved.append(
                f"{module} (distribution candidates: {', '.join(candidates) or 'none'})"
            )
            continue

        distribution = canonical_distribution_name(installed[0])
        resolved.setdefault(distribution, set()).add(module)

    runtime_distributions = dict(RUNTIME_DISTRIBUTIONS)
    resolved_names = {normalize_distribution_name(name) for name in resolved}
    for trigger, dependencies in CONDITIONAL_RUNTIME_DISTRIBUTIONS.items():
        if trigger in resolved_names:
            runtime_distributions.update(dependencies)

    for distribution in runtime_distributions:
        try:
            metadata.version(distribution)
        except metadata.PackageNotFoundError:
            unresolved.append(
                f"runtime dependency {distribution} "
                f"({runtime_distributions[distribution]})"
            )
            continue
        resolved.setdefault(canonical_distribution_name(distribution), set()).add("<runtime>")

    return resolved, unresolved


def render_requirements(distributions: Iterable[str], pin_versions: bool) -> str:
    """Render deterministic requirements.txt content."""
    distributions = sorted(distributions, key=normalize_distribution_name)
    manual = [
        name
        for name in distributions
        if normalize_distribution_name(name) in MANUAL_DISTRIBUTIONS
    ]
    installable = [name for name in distributions if name not in manual]

    lines = []
    for distribution in installable:
        if pin_versions:
            # CUDA/CPU wheel variants use local labels such as ``+cu128``.
            # Pin the public version and let the selected package index decide
            # the platform build, so the file also works with another CUDA ABI.
            version = metadata.version(distribution).split("+", 1)[0]
            lines.append(f"{distribution}=={version}")
        else:
            lines.append(distribution)

    manual_lines = []
    if manual:
        manual_lines.extend(
            [
                "#",
                "# Manual compatibility install(s), required only by the corresponding baseline:",
            ]
        )
        for distribution in manual:
            requirement = distribution
            if pin_versions:
                version = metadata.version(distribution).split("+", 1)[0]
                requirement = f"{distribution}=={version}"
            reason = MANUAL_DISTRIBUTIONS[normalize_distribution_name(distribution)]
            manual_lines.append(f"# {requirement}: {reason}.")
            manual_lines.append(f"#   python -m pip install --no-deps {requirement}")

    body = "\n".join(lines + manual_lines)
    return HEADER + body + "\n"


def existing_requirement_names(path: Path) -> set[str]:
    """Read distribution names from an existing simple requirements file."""
    if not path.exists():
        return set()
    names = set()
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", "-")):
            continue
        name = re.split(r"[<>=!~;\[]", line, maxsplit=1)[0].strip()
        if name:
            names.add(normalize_distribution_name(name))
    return names


def build_parser() -> argparse.ArgumentParser:
    default_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Generate requirements.txt from direct repository imports."
    )
    parser.add_argument("--root", type=Path, default=default_root)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--exclude", action="append", default=[])
    parser.add_argument("--no-pin", action="store_true", help="Omit installed versions.")
    parser.add_argument("--check", action="store_true", help="Fail if the output is stale.")
    parser.add_argument("--dry-run", action="store_true", help="Print without writing.")
    parser.add_argument("--verbose", action="store_true", help="Show import mappings.")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    root = args.root.resolve()
    output = (args.output or root / "requirements.txt").resolve()
    excluded_dirs = DEFAULT_EXCLUDED_DIRS | set(args.exclude)

    imports = scan_imports(root, excluded_dirs)
    local_modules = discover_local_modules(root, excluded_dirs)
    distributions, unresolved = resolve_distributions(imports, local_modules)
    if unresolved:
        details = "\n".join(f"  - {item}" for item in unresolved)
        print(
            "Unable to map every external import to exactly one installed distribution:\n"
            f"{details}\n"
            "Install the missing package or add an explicit MODULE_TO_DISTRIBUTION mapping.",
            file=sys.stderr,
        )
        return 2

    content = render_requirements(distributions, pin_versions=not args.no_pin)
    old_content = output.read_text(encoding="utf-8-sig") if output.exists() else ""

    if args.verbose:
        for distribution in sorted(distributions, key=normalize_distribution_name):
            modules = ", ".join(sorted(distributions[distribution]))
            print(f"{distribution}: {modules}")

    if args.dry_run:
        print(content, end="")
        return 0

    if args.check:
        if old_content == content:
            manual_count = sum(
                normalize_distribution_name(name) in MANUAL_DISTRIBUTIONS
                for name in distributions
            )
            print(
                f"{output} is up to date "
                f"({len(distributions) - manual_count} installable + "
                f"{manual_count} manual dependencies)."
            )
            return 0
        print(f"{output} is out of date.", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                old_content.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(output),
                tofile="generated requirements",
            )
        )
        return 1

    old_names = existing_requirement_names(output)
    new_names = {
        normalize_distribution_name(name)
        for name in distributions
        if normalize_distribution_name(name) not in MANUAL_DISTRIBUTIONS
    }
    output.write_text(content, encoding="utf-8", newline="\n")
    manual_names = sorted(
        name
        for name in distributions
        if normalize_distribution_name(name) in MANUAL_DISTRIBUTIONS
    )
    print(f"Wrote {len(new_names)} installable dependencies to {output}")
    if manual_names:
        print("Documented manual compatibility installs: " + ", ".join(manual_names))
    if added := sorted(new_names - old_names):
        print("Added: " + ", ".join(added))
    if removed := sorted(old_names - new_names):
        print("Removed: " + ", ".join(removed))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
